all:
	make -C c
	make -C cs
	make -C java
	make -C js
	make -C php
	make -C python
	make -C ruby

clean:
	make -C c clean
	make -C cs clean
	make -C java clean
	make -C js clean
	make -C php clean
	make -C python clean
	make -C ruby clean
