#!/bin/bash

for dir in *
do
	if [ -d $dir ]
	then
		echo "Running $dir tests..."
		cd $dir
		./version > result
		for test_run in {1..10}
		do
			./performance >> result
		done
		cd ..
	fi
done

node gen_report.js
